### ISSUE TITLE
能否发布到脚本市场

### ISSUE THREAD

**Issue by miscommunication** [unlimitbladeworks/douyin-autojs#1]
不错的脚本，围绕抖音，感觉可以做很多事情，可否发布到 hamibot 脚本市场 https://hamibot.com/marketplace ，方便使用

**Comment by unlimitbladeworks** [comment]
@miscommunication 没问题，既然开源出来了，当然希望更多人用得到 😄

**Comment by unlimitbladeworks** [comment]
> 不错的脚本，围绕抖音，感觉可以做很多事情，可否发布到 hamibot 脚本市场 https://hamibot.com/marketplace ，方便使用

**Comment by unlimitbladeworks** [comment]
> 不错的脚本，围绕抖音，感觉可以做很多事情，可否发布到 hamibot 脚本市场 https://hamibot.com/marketplace ，方便使用

没问题，既然开源出来了，当然希望更多人用得到 😄

**Comment by miscommunication** [comment]
哈哈，我是小白，我只会市场里那种一键安装的 🤦‍♂️
